name: Auto-Update Database

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug: Print Working Directory & List Files
        run: |
          echo "📂 Current Directory: $(pwd)"
          echo "📝 Listing Root Files..."
          ls -la
          echo "📂 Checking Ekankik_QS/my-app..."
          ls -la Ekankik_QS/my-app || echo "❌ Directory missing!"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Database Update Script
        id: update_db
        run: |
          if python Ekankik_QS/my-app/backend/update/populateDB.py; then
            echo "✅ Database update successful" 
            echo "update_status=success" >> $GITHUB_ENV
          else
            echo "❌ Database update failed"
            echo "update_status=failure" >> $GITHUB_ENV
            exit 1
          fi

      - name: Commit and Push Changes
        if: env.update_status == 'success'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check for changes before committing
          if git diff --staged --quiet; then
            echo "⚠️ No changes to commit"
            exit 0
          fi
          
          DATE=$(date +'%Y-%m-%d %H:%M:%S UTC')
          git commit -m "Auto-update: Database and JSON files on $DATE"
          git push
        continue-on-error: true

      - name: Report Failure
        if: failure()
        run: |
          echo "❌ Database update failed. Check logs for details."
          exit 1
